-- Acest fișier a fost înlocuit de 8_decision_lab_debrief.sql
-- (aceleași 5 scenarii, plus trait pe fiecare opțiune + profil de decizie
-- calculat la finalul jocului). Nu-l mai rula pe instalări noi.
